const moment = require("moment")
require("../momentkh")(moment)
const {getKhNewYearMoment2} = require("../momentkh")(moment)
console.log(getKhNewYearMoment2(2024))
console.log(moment.getKhNewYearMoment(2021))
